# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/koitt/Vivado_Workspace/uart/uart.srcs/sources_1/bd/uart_system/ip/uart_system_processing_system7_0_0/uart_system_processing_system7_0_0.xci
# IP: The module: 'uart_system_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/koitt/Vivado_Workspace/uart/uart.srcs/sources_1/bd/uart_system/ip/uart_system_processing_system7_0_0/uart_system_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'uart_system_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/koitt/Vivado_Workspace/uart/uart.srcs/sources_1/bd/uart_system/ip/uart_system_processing_system7_0_0/uart_system_processing_system7_0_0.xci
# IP: The module: 'uart_system_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/koitt/Vivado_Workspace/uart/uart.srcs/sources_1/bd/uart_system/ip/uart_system_processing_system7_0_0/uart_system_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'uart_system_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
