set_property IOSTANDARD LVCMOS33 [get_ports SPI0_MISO_O_0]
set_property IOSTANDARD LVCMOS33 [get_ports SPI0_MOSI_O_0]
set_property IOSTANDARD LVCMOS33 [get_ports SPI0_SCLK_O_0]
set_property PACKAGE_PIN W15 [get_ports SPI0_MOSI_O_0]
set_property PACKAGE_PIN T10 [get_ports SPI0_SCLK_O_0]
set_property PACKAGE_PIN T11 [get_ports SPI0_MISO_O_0]

set_property IOSTANDARD LVCMOS33 [get_ports SPI0_MISO_I_0]
set_property IOSTANDARD LVCMOS33 [get_ports SPI0_SS_O_0]
set_property PACKAGE_PIN T11 [get_ports SPI0_MISO_I_0]
set_property PACKAGE_PIN V15 [get_ports SPI0_SS_O_0]
