# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/wrg/tmp/Zybo-Z7-Master.xdc

# Block Designs: bd/system/system.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system || ORIG_REF_NAME==system} -quiet] -quiet

# IP: bd/system/ip/system_counter_0_0/system_counter_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_counter_0_0 || ORIG_REF_NAME==system_counter_0_0} -quiet] -quiet

# IP: bd/system/ip/system_counter_1_0/system_counter_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_counter_1_0 || ORIG_REF_NAME==system_counter_1_0} -quiet] -quiet

# IP: bd/system/ip/system_lut_0_0/system_lut_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_lut_0_0 || ORIG_REF_NAME==system_lut_0_0} -quiet] -quiet

# IP: bd/system/ip/system_xlconstant_0_0/system_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xlconstant_0_0 || ORIG_REF_NAME==system_xlconstant_0_0} -quiet] -quiet

# XDC: bd/system/system_ooc.xdc
