# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/roro/fpga_workspace/ps_spi/ps_spi.srcs/sources_1/bd/ps_spi/ip/ps_spi_processing_system7_0_0/ps_spi_processing_system7_0_0.xci
# IP: The module: 'ps_spi_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/roro/fpga_workspace/ps_spi/ps_spi.srcs/sources_1/bd/ps_spi/ip/ps_spi_processing_system7_0_0/ps_spi_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'ps_spi_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/roro/fpga_workspace/ps_spi/ps_spi.srcs/sources_1/bd/ps_spi/ip/ps_spi_processing_system7_0_0/ps_spi_processing_system7_0_0.xci
# IP: The module: 'ps_spi_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/roro/fpga_workspace/ps_spi/ps_spi.srcs/sources_1/bd/ps_spi/ip/ps_spi_processing_system7_0_0/ps_spi_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'ps_spi_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
