################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Each subdirectory must supply rules for building sources it contributes
FreeRTOS-Plus-FAT/ff_error.null: ../FreeRTOS-Plus-FAT/ff_error.c
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"/include" "/home/koitt/project/IntegrationProject/coffee_machine/mpu/LaunchPad_FreeRTOS_Ethernet/source" "/home/koitt/project/IntegrationProject/coffee_machine/mpu/LaunchPad_FreeRTOS_Ethernet/include" "/home/koitt/project/IntegrationProject/coffee_machine/mpu/LaunchPad_FreeRTOS_Ethernet/FreeRTOS-Plus-CLI" "/home/koitt/project/IntegrationProject/coffee_machine/mpu/LaunchPad_FreeRTOS_Ethernet/FreeRTOS-Plus-CLI/include" "/home/koitt/project/IntegrationProject/coffee_machine/mpu/LaunchPad_FreeRTOS_Ethernet/FreeRTOS-Plus-IO/Include" "/home/koitt/project/IntegrationProject/coffee_machine/mpu/LaunchPad_FreeRTOS_Ethernet/FreeRTOS-Plus-IO/Device/tms570ls20x31x/include" "/home/koitt/project/IntegrationProject/coffee_machine/mpu/LaunchPad_FreeRTOS_Ethernet/FreeRTOS-Plus-IO/Device/tms570ls20x31x/SupportedBoards" "/home/koitt/project/IntegrationProject/coffee_machine/mpu/LaunchPad_FreeRTOS_Ethernet/FreeRTOS-Plus-TCP/include" "/home/koitt/project/IntegrationProject/coffee_machine/mpu/LaunchPad_FreeRTOS_Ethernet/FreeRTOS-Plus-TCP/protocols/include" "/home/koitt/project/IntegrationProject/coffee_machine/mpu/LaunchPad_FreeRTOS_Ethernet/FreeRTOS-Plus-TCP/portable/Compiler/CCS" "/home/koitt/project/IntegrationProject/coffee_machine/mpu/LaunchPad_FreeRTOS_Ethernet/FreeRTOS-Plus-TCP" "/home/koitt/project/IntegrationProject/coffee_machine/mpu/LaunchPad_FreeRTOS_Ethernet/FreeRTOS-Plus-FAT/include" "/home/koitt/project/IntegrationProject/coffee_machine/mpu/LaunchPad_FreeRTOS_Ethernet/FreeRTOS-Plus-FAT/portable/common" "/home/koitt/project/IntegrationProject/coffee_machine/mpu/LaunchPad_FreeRTOS_Ethernet/FreeRTOS-Plus-UDP-Console/include" "/home/koitt/project/IntegrationProject/coffee_machine/mpu/LaunchPad_FreeRTOS_Ethernet/FreeRTOS-Plus-UART-Console/include" 225  "$@" "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

FreeRTOS-Plus-FAT/ff_ioman.null: ../FreeRTOS-Plus-FAT/ff_ioman.c
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"/include" "/home/koitt/project/IntegrationProject/coffee_machine/mpu/LaunchPad_FreeRTOS_Ethernet/source" "/home/koitt/project/IntegrationProject/coffee_machine/mpu/LaunchPad_FreeRTOS_Ethernet/include" "/home/koitt/project/IntegrationProject/coffee_machine/mpu/LaunchPad_FreeRTOS_Ethernet/FreeRTOS-Plus-CLI" "/home/koitt/project/IntegrationProject/coffee_machine/mpu/LaunchPad_FreeRTOS_Ethernet/FreeRTOS-Plus-CLI/include" "/home/koitt/project/IntegrationProject/coffee_machine/mpu/LaunchPad_FreeRTOS_Ethernet/FreeRTOS-Plus-IO/Include" "/home/koitt/project/IntegrationProject/coffee_machine/mpu/LaunchPad_FreeRTOS_Ethernet/FreeRTOS-Plus-IO/Device/tms570ls20x31x/include" "/home/koitt/project/IntegrationProject/coffee_machine/mpu/LaunchPad_FreeRTOS_Ethernet/FreeRTOS-Plus-IO/Device/tms570ls20x31x/SupportedBoards" "/home/koitt/project/IntegrationProject/coffee_machine/mpu/LaunchPad_FreeRTOS_Ethernet/FreeRTOS-Plus-TCP/include" "/home/koitt/project/IntegrationProject/coffee_machine/mpu/LaunchPad_FreeRTOS_Ethernet/FreeRTOS-Plus-TCP/protocols/include" "/home/koitt/project/IntegrationProject/coffee_machine/mpu/LaunchPad_FreeRTOS_Ethernet/FreeRTOS-Plus-TCP/portable/Compiler/CCS" "/home/koitt/project/IntegrationProject/coffee_machine/mpu/LaunchPad_FreeRTOS_Ethernet/FreeRTOS-Plus-TCP" "/home/koitt/project/IntegrationProject/coffee_machine/mpu/LaunchPad_FreeRTOS_Ethernet/FreeRTOS-Plus-FAT/include" "/home/koitt/project/IntegrationProject/coffee_machine/mpu/LaunchPad_FreeRTOS_Ethernet/FreeRTOS-Plus-FAT/portable/common" "/home/koitt/project/IntegrationProject/coffee_machine/mpu/LaunchPad_FreeRTOS_Ethernet/FreeRTOS-Plus-UDP-Console/include" "/home/koitt/project/IntegrationProject/coffee_machine/mpu/LaunchPad_FreeRTOS_Ethernet/FreeRTOS-Plus-UART-Console/include" 225  "$@" "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

FreeRTOS-Plus-FAT/ff_memory.null: ../FreeRTOS-Plus-FAT/ff_memory.c
	@echo 'Building file: "$<"'
	@echo 'Invoking: ARM Compiler'
	"/include" "/home/koitt/project/IntegrationProject/coffee_machine/mpu/LaunchPad_FreeRTOS_Ethernet/source" "/home/koitt/project/IntegrationProject/coffee_machine/mpu/LaunchPad_FreeRTOS_Ethernet/include" "/home/koitt/project/IntegrationProject/coffee_machine/mpu/LaunchPad_FreeRTOS_Ethernet/FreeRTOS-Plus-CLI" "/home/koitt/project/IntegrationProject/coffee_machine/mpu/LaunchPad_FreeRTOS_Ethernet/FreeRTOS-Plus-CLI/include" "/home/koitt/project/IntegrationProject/coffee_machine/mpu/LaunchPad_FreeRTOS_Ethernet/FreeRTOS-Plus-IO/Include" "/home/koitt/project/IntegrationProject/coffee_machine/mpu/LaunchPad_FreeRTOS_Ethernet/FreeRTOS-Plus-IO/Device/tms570ls20x31x/include" "/home/koitt/project/IntegrationProject/coffee_machine/mpu/LaunchPad_FreeRTOS_Ethernet/FreeRTOS-Plus-IO/Device/tms570ls20x31x/SupportedBoards" "/home/koitt/project/IntegrationProject/coffee_machine/mpu/LaunchPad_FreeRTOS_Ethernet/FreeRTOS-Plus-TCP/include" "/home/koitt/project/IntegrationProject/coffee_machine/mpu/LaunchPad_FreeRTOS_Ethernet/FreeRTOS-Plus-TCP/protocols/include" "/home/koitt/project/IntegrationProject/coffee_machine/mpu/LaunchPad_FreeRTOS_Ethernet/FreeRTOS-Plus-TCP/portable/Compiler/CCS" "/home/koitt/project/IntegrationProject/coffee_machine/mpu/LaunchPad_FreeRTOS_Ethernet/FreeRTOS-Plus-TCP" "/home/koitt/project/IntegrationProject/coffee_machine/mpu/LaunchPad_FreeRTOS_Ethernet/FreeRTOS-Plus-FAT/include" "/home/koitt/project/IntegrationProject/coffee_machine/mpu/LaunchPad_FreeRTOS_Ethernet/FreeRTOS-Plus-FAT/portable/common" "/home/koitt/project/IntegrationProject/coffee_machine/mpu/LaunchPad_FreeRTOS_Ethernet/FreeRTOS-Plus-UDP-Console/include" "/home/koitt/project/IntegrationProject/coffee_machine/mpu/LaunchPad_FreeRTOS_Ethernet/FreeRTOS-Plus-UART-Console/include" 225  "$@" "$<"
	@echo 'Finished building: "$<"'
	@echo ' '


