set_property SRC_FILE_INFO {cfile:/home/roro/fpga_workspace/ps_spi/ps_spi.srcs/constrs_1/new/ps_spi.xdc rfile:../../../ps_spi.srcs/constrs_1/new/ps_spi.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports SPI0_MISO_O_0]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W15 [get_ports SPI0_MOSI_O_0]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T10 [get_ports SPI0_SCLK_O_0]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T11 [get_ports SPI0_MISO_O_0]
