################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Each subdirectory must supply rules for building sources it contributes
source/HL_adc.obj: ../source/HL_adc.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_15.12.4.LTS/bin/armcl" -mv7R5 --code_state=32 --float_support=VFPv3D16 -O4 --opt_for_speed=0 --fp_mode=relaxed --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_15.12.4.LTS/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/source" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-CLI" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-CLI/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-IO/Include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-IO/Device/tms570ls20x31x/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-IO/Device/tms570ls20x31x/SupportedBoards" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP/protocols/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP/portable/Compiler/CCS" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-FAT/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-FAT/portable/common" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-UDP-Console/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-UART-Console/include" -g --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --enum_type=packed --preproc_with_compile --preproc_dependency="source/HL_adc.d" --obj_directory="source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

source/HL_crc.obj: ../source/HL_crc.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_15.12.4.LTS/bin/armcl" -mv7R5 --code_state=32 --float_support=VFPv3D16 -O4 --opt_for_speed=0 --fp_mode=relaxed --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_15.12.4.LTS/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/source" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-CLI" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-CLI/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-IO/Include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-IO/Device/tms570ls20x31x/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-IO/Device/tms570ls20x31x/SupportedBoards" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP/protocols/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP/portable/Compiler/CCS" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-FAT/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-FAT/portable/common" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-UDP-Console/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-UART-Console/include" -g --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --enum_type=packed --preproc_with_compile --preproc_dependency="source/HL_crc.d" --obj_directory="source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

source/HL_ecap.obj: ../source/HL_ecap.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_15.12.4.LTS/bin/armcl" -mv7R5 --code_state=32 --float_support=VFPv3D16 -O4 --opt_for_speed=0 --fp_mode=relaxed --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_15.12.4.LTS/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/source" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-CLI" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-CLI/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-IO/Include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-IO/Device/tms570ls20x31x/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-IO/Device/tms570ls20x31x/SupportedBoards" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP/protocols/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP/portable/Compiler/CCS" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-FAT/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-FAT/portable/common" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-UDP-Console/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-UART-Console/include" -g --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --enum_type=packed --preproc_with_compile --preproc_dependency="source/HL_ecap.d" --obj_directory="source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

source/HL_epc.obj: ../source/HL_epc.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_15.12.4.LTS/bin/armcl" -mv7R5 --code_state=32 --float_support=VFPv3D16 -O4 --opt_for_speed=0 --fp_mode=relaxed --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_15.12.4.LTS/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/source" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-CLI" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-CLI/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-IO/Include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-IO/Device/tms570ls20x31x/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-IO/Device/tms570ls20x31x/SupportedBoards" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP/protocols/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP/portable/Compiler/CCS" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-FAT/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-FAT/portable/common" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-UDP-Console/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-UART-Console/include" -g --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --enum_type=packed --preproc_with_compile --preproc_dependency="source/HL_epc.d" --obj_directory="source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

source/HL_errata.obj: ../source/HL_errata.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_15.12.4.LTS/bin/armcl" -mv7R5 --code_state=32 --float_support=VFPv3D16 -O4 --opt_for_speed=0 --fp_mode=relaxed --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_15.12.4.LTS/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/source" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-CLI" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-CLI/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-IO/Include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-IO/Device/tms570ls20x31x/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-IO/Device/tms570ls20x31x/SupportedBoards" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP/protocols/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP/portable/Compiler/CCS" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-FAT/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-FAT/portable/common" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-UDP-Console/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-UART-Console/include" -g --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --enum_type=packed --preproc_with_compile --preproc_dependency="source/HL_errata.d" --obj_directory="source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

source/HL_esm.obj: ../source/HL_esm.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_15.12.4.LTS/bin/armcl" -mv7R5 --code_state=32 --float_support=VFPv3D16 -O4 --opt_for_speed=0 --fp_mode=relaxed --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_15.12.4.LTS/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/source" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-CLI" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-CLI/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-IO/Include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-IO/Device/tms570ls20x31x/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-IO/Device/tms570ls20x31x/SupportedBoards" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP/protocols/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP/portable/Compiler/CCS" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-FAT/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-FAT/portable/common" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-UDP-Console/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-UART-Console/include" -g --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --enum_type=packed --preproc_with_compile --preproc_dependency="source/HL_esm.d" --obj_directory="source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

source/HL_etpwm.obj: ../source/HL_etpwm.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_15.12.4.LTS/bin/armcl" -mv7R5 --code_state=32 --float_support=VFPv3D16 -O4 --opt_for_speed=0 --fp_mode=relaxed --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_15.12.4.LTS/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/source" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-CLI" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-CLI/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-IO/Include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-IO/Device/tms570ls20x31x/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-IO/Device/tms570ls20x31x/SupportedBoards" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP/protocols/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP/portable/Compiler/CCS" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-FAT/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-FAT/portable/common" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-UDP-Console/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-UART-Console/include" -g --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --enum_type=packed --preproc_with_compile --preproc_dependency="source/HL_etpwm.d" --obj_directory="source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

source/HL_gio.obj: ../source/HL_gio.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_15.12.4.LTS/bin/armcl" -mv7R5 --code_state=32 --float_support=VFPv3D16 -O4 --opt_for_speed=0 --fp_mode=relaxed --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_15.12.4.LTS/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/source" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-CLI" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-CLI/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-IO/Include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-IO/Device/tms570ls20x31x/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-IO/Device/tms570ls20x31x/SupportedBoards" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP/protocols/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP/portable/Compiler/CCS" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-FAT/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-FAT/portable/common" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-UDP-Console/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-UART-Console/include" -g --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --enum_type=packed --preproc_with_compile --preproc_dependency="source/HL_gio.d" --obj_directory="source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

source/HL_mdio.obj: ../source/HL_mdio.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_15.12.4.LTS/bin/armcl" -mv7R5 --code_state=32 --float_support=VFPv3D16 -O4 --opt_for_speed=0 --fp_mode=relaxed --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_15.12.4.LTS/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/source" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-CLI" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-CLI/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-IO/Include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-IO/Device/tms570ls20x31x/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-IO/Device/tms570ls20x31x/SupportedBoards" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP/protocols/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP/portable/Compiler/CCS" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-FAT/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-FAT/portable/common" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-UDP-Console/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-UART-Console/include" -g --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --enum_type=packed --preproc_with_compile --preproc_dependency="source/HL_mdio.d" --obj_directory="source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

source/HL_nmpu.obj: ../source/HL_nmpu.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_15.12.4.LTS/bin/armcl" -mv7R5 --code_state=32 --float_support=VFPv3D16 -O4 --opt_for_speed=0 --fp_mode=relaxed --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_15.12.4.LTS/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/source" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-CLI" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-CLI/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-IO/Include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-IO/Device/tms570ls20x31x/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-IO/Device/tms570ls20x31x/SupportedBoards" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP/protocols/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP/portable/Compiler/CCS" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-FAT/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-FAT/portable/common" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-UDP-Console/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-UART-Console/include" -g --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --enum_type=packed --preproc_with_compile --preproc_dependency="source/HL_nmpu.d" --obj_directory="source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

source/HL_notification.obj: ../source/HL_notification.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_15.12.4.LTS/bin/armcl" -mv7R5 --code_state=32 --float_support=VFPv3D16 -O4 --opt_for_speed=0 --fp_mode=relaxed --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_15.12.4.LTS/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/source" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-CLI" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-CLI/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-IO/Include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-IO/Device/tms570ls20x31x/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-IO/Device/tms570ls20x31x/SupportedBoards" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP/protocols/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP/portable/Compiler/CCS" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-FAT/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-FAT/portable/common" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-UDP-Console/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-UART-Console/include" -g --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --enum_type=packed --preproc_with_compile --preproc_dependency="source/HL_notification.d" --obj_directory="source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

source/HL_phy_dp83640.obj: ../source/HL_phy_dp83640.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_15.12.4.LTS/bin/armcl" -mv7R5 --code_state=32 --float_support=VFPv3D16 -O4 --opt_for_speed=0 --fp_mode=relaxed --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_15.12.4.LTS/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/source" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-CLI" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-CLI/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-IO/Include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-IO/Device/tms570ls20x31x/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-IO/Device/tms570ls20x31x/SupportedBoards" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP/protocols/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP/portable/Compiler/CCS" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-FAT/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-FAT/portable/common" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-UDP-Console/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-UART-Console/include" -g --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --enum_type=packed --preproc_with_compile --preproc_dependency="source/HL_phy_dp83640.d" --obj_directory="source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

source/HL_pinmux.obj: ../source/HL_pinmux.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_15.12.4.LTS/bin/armcl" -mv7R5 --code_state=32 --float_support=VFPv3D16 -O4 --opt_for_speed=0 --fp_mode=relaxed --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_15.12.4.LTS/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/source" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-CLI" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-CLI/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-IO/Include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-IO/Device/tms570ls20x31x/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-IO/Device/tms570ls20x31x/SupportedBoards" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP/protocols/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP/portable/Compiler/CCS" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-FAT/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-FAT/portable/common" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-UDP-Console/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-UART-Console/include" -g --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --enum_type=packed --preproc_with_compile --preproc_dependency="source/HL_pinmux.d" --obj_directory="source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

source/HL_sys_core.obj: ../source/HL_sys_core.asm $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_15.12.4.LTS/bin/armcl" -mv7R5 --code_state=32 --float_support=VFPv3D16 -O4 --opt_for_speed=0 --fp_mode=relaxed --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_15.12.4.LTS/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/source" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-CLI" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-CLI/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-IO/Include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-IO/Device/tms570ls20x31x/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-IO/Device/tms570ls20x31x/SupportedBoards" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP/protocols/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP/portable/Compiler/CCS" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-FAT/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-FAT/portable/common" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-UDP-Console/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-UART-Console/include" -g --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --enum_type=packed --preproc_with_compile --preproc_dependency="source/HL_sys_core.d" --obj_directory="source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

source/HL_sys_dma.obj: ../source/HL_sys_dma.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_15.12.4.LTS/bin/armcl" -mv7R5 --code_state=32 --float_support=VFPv3D16 -O4 --opt_for_speed=0 --fp_mode=relaxed --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_15.12.4.LTS/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/source" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-CLI" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-CLI/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-IO/Include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-IO/Device/tms570ls20x31x/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-IO/Device/tms570ls20x31x/SupportedBoards" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP/protocols/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP/portable/Compiler/CCS" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-FAT/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-FAT/portable/common" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-UDP-Console/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-UART-Console/include" -g --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --enum_type=packed --preproc_with_compile --preproc_dependency="source/HL_sys_dma.d" --obj_directory="source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

source/HL_sys_intvecs.obj: ../source/HL_sys_intvecs.asm $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_15.12.4.LTS/bin/armcl" -mv7R5 --code_state=32 --float_support=VFPv3D16 -O4 --opt_for_speed=0 --fp_mode=relaxed --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_15.12.4.LTS/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/source" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-CLI" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-CLI/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-IO/Include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-IO/Device/tms570ls20x31x/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-IO/Device/tms570ls20x31x/SupportedBoards" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP/protocols/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP/portable/Compiler/CCS" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-FAT/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-FAT/portable/common" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-UDP-Console/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-UART-Console/include" -g --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --enum_type=packed --preproc_with_compile --preproc_dependency="source/HL_sys_intvecs.d" --obj_directory="source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

source/HL_sys_mpu.obj: ../source/HL_sys_mpu.asm $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_15.12.4.LTS/bin/armcl" -mv7R5 --code_state=32 --float_support=VFPv3D16 -O4 --opt_for_speed=0 --fp_mode=relaxed --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_15.12.4.LTS/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/source" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-CLI" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-CLI/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-IO/Include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-IO/Device/tms570ls20x31x/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-IO/Device/tms570ls20x31x/SupportedBoards" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP/protocols/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP/portable/Compiler/CCS" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-FAT/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-FAT/portable/common" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-UDP-Console/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-UART-Console/include" -g --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --enum_type=packed --preproc_with_compile --preproc_dependency="source/HL_sys_mpu.d" --obj_directory="source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

source/HL_sys_pcr.obj: ../source/HL_sys_pcr.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_15.12.4.LTS/bin/armcl" -mv7R5 --code_state=32 --float_support=VFPv3D16 -O4 --opt_for_speed=0 --fp_mode=relaxed --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_15.12.4.LTS/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/source" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-CLI" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-CLI/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-IO/Include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-IO/Device/tms570ls20x31x/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-IO/Device/tms570ls20x31x/SupportedBoards" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP/protocols/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP/portable/Compiler/CCS" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-FAT/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-FAT/portable/common" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-UDP-Console/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-UART-Console/include" -g --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --enum_type=packed --preproc_with_compile --preproc_dependency="source/HL_sys_pcr.d" --obj_directory="source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

source/HL_sys_phantom.obj: ../source/HL_sys_phantom.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_15.12.4.LTS/bin/armcl" -mv7R5 --code_state=32 --float_support=VFPv3D16 -O4 --opt_for_speed=0 --fp_mode=relaxed --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_15.12.4.LTS/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/source" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-CLI" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-CLI/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-IO/Include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-IO/Device/tms570ls20x31x/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-IO/Device/tms570ls20x31x/SupportedBoards" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP/protocols/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP/portable/Compiler/CCS" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-FAT/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-FAT/portable/common" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-UDP-Console/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-UART-Console/include" -g --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --enum_type=packed --preproc_with_compile --preproc_dependency="source/HL_sys_phantom.d" --obj_directory="source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

source/HL_sys_pmm.obj: ../source/HL_sys_pmm.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_15.12.4.LTS/bin/armcl" -mv7R5 --code_state=32 --float_support=VFPv3D16 -O4 --opt_for_speed=0 --fp_mode=relaxed --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_15.12.4.LTS/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/source" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-CLI" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-CLI/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-IO/Include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-IO/Device/tms570ls20x31x/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-IO/Device/tms570ls20x31x/SupportedBoards" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP/protocols/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP/portable/Compiler/CCS" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-FAT/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-FAT/portable/common" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-UDP-Console/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-UART-Console/include" -g --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --enum_type=packed --preproc_with_compile --preproc_dependency="source/HL_sys_pmm.d" --obj_directory="source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

source/HL_sys_pmu.obj: ../source/HL_sys_pmu.asm $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_15.12.4.LTS/bin/armcl" -mv7R5 --code_state=32 --float_support=VFPv3D16 -O4 --opt_for_speed=0 --fp_mode=relaxed --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_15.12.4.LTS/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/source" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-CLI" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-CLI/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-IO/Include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-IO/Device/tms570ls20x31x/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-IO/Device/tms570ls20x31x/SupportedBoards" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP/protocols/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP/portable/Compiler/CCS" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-FAT/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-FAT/portable/common" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-UDP-Console/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-UART-Console/include" -g --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --enum_type=packed --preproc_with_compile --preproc_dependency="source/HL_sys_pmu.d" --obj_directory="source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

source/HL_sys_startup.obj: ../source/HL_sys_startup.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_15.12.4.LTS/bin/armcl" -mv7R5 --code_state=32 --float_support=VFPv3D16 -O4 --opt_for_speed=0 --fp_mode=relaxed --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_15.12.4.LTS/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/source" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-CLI" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-CLI/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-IO/Include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-IO/Device/tms570ls20x31x/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-IO/Device/tms570ls20x31x/SupportedBoards" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP/protocols/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP/portable/Compiler/CCS" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-FAT/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-FAT/portable/common" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-UDP-Console/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-UART-Console/include" -g --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --enum_type=packed --preproc_with_compile --preproc_dependency="source/HL_sys_startup.d" --obj_directory="source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

source/HL_sys_vim.obj: ../source/HL_sys_vim.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_15.12.4.LTS/bin/armcl" -mv7R5 --code_state=32 --float_support=VFPv3D16 -O4 --opt_for_speed=0 --fp_mode=relaxed --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_15.12.4.LTS/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/source" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-CLI" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-CLI/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-IO/Include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-IO/Device/tms570ls20x31x/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-IO/Device/tms570ls20x31x/SupportedBoards" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP/protocols/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP/portable/Compiler/CCS" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-FAT/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-FAT/portable/common" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-UDP-Console/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-UART-Console/include" -g --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --enum_type=packed --preproc_with_compile --preproc_dependency="source/HL_sys_vim.d" --obj_directory="source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

source/HL_system.obj: ../source/HL_system.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_15.12.4.LTS/bin/armcl" -mv7R5 --code_state=32 --float_support=VFPv3D16 -O4 --opt_for_speed=0 --fp_mode=relaxed --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_15.12.4.LTS/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/source" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-CLI" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-CLI/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-IO/Include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-IO/Device/tms570ls20x31x/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-IO/Device/tms570ls20x31x/SupportedBoards" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP/protocols/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP/portable/Compiler/CCS" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-FAT/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-FAT/portable/common" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-UDP-Console/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-UART-Console/include" -g --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --enum_type=packed --preproc_with_compile --preproc_dependency="source/HL_system.d" --obj_directory="source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

source/ma_date_and_time.obj: ../source/ma_date_and_time.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_15.12.4.LTS/bin/armcl" -mv7R5 --code_state=32 --float_support=VFPv3D16 -O4 --opt_for_speed=0 --fp_mode=relaxed --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_15.12.4.LTS/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/source" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-CLI" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-CLI/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-IO/Include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-IO/Device/tms570ls20x31x/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-IO/Device/tms570ls20x31x/SupportedBoards" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP/protocols/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP/portable/Compiler/CCS" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-FAT/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-FAT/portable/common" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-UDP-Console/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-UART-Console/include" -g --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --enum_type=packed --preproc_with_compile --preproc_dependency="source/ma_date_and_time.d" --obj_directory="source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

source/main.obj: ../source/main.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_15.12.4.LTS/bin/armcl" -mv7R5 --code_state=32 --float_support=VFPv3D16 -O4 --opt_for_speed=0 --fp_mode=relaxed --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_15.12.4.LTS/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/source" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-CLI" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-CLI/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-IO/Include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-IO/Device/tms570ls20x31x/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-IO/Device/tms570ls20x31x/SupportedBoards" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP/protocols/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP/portable/Compiler/CCS" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-FAT/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-FAT/portable/common" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-UDP-Console/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-UART-Console/include" -g --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --enum_type=packed --preproc_with_compile --preproc_dependency="source/main.d" --obj_directory="source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

source/os_croutine.obj: ../source/os_croutine.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_15.12.4.LTS/bin/armcl" -mv7R5 --code_state=32 --float_support=VFPv3D16 -O4 --opt_for_speed=0 --fp_mode=relaxed --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_15.12.4.LTS/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/source" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-CLI" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-CLI/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-IO/Include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-IO/Device/tms570ls20x31x/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-IO/Device/tms570ls20x31x/SupportedBoards" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP/protocols/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP/portable/Compiler/CCS" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-FAT/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-FAT/portable/common" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-UDP-Console/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-UART-Console/include" -g --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --enum_type=packed --preproc_with_compile --preproc_dependency="source/os_croutine.d" --obj_directory="source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

source/os_event_groups.obj: ../source/os_event_groups.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_15.12.4.LTS/bin/armcl" -mv7R5 --code_state=32 --float_support=VFPv3D16 -O4 --opt_for_speed=0 --fp_mode=relaxed --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_15.12.4.LTS/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/source" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-CLI" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-CLI/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-IO/Include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-IO/Device/tms570ls20x31x/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-IO/Device/tms570ls20x31x/SupportedBoards" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP/protocols/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP/portable/Compiler/CCS" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-FAT/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-FAT/portable/common" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-UDP-Console/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-UART-Console/include" -g --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --enum_type=packed --preproc_with_compile --preproc_dependency="source/os_event_groups.d" --obj_directory="source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

source/os_heap.obj: ../source/os_heap.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_15.12.4.LTS/bin/armcl" -mv7R5 --code_state=32 --float_support=VFPv3D16 -O4 --opt_for_speed=0 --fp_mode=relaxed --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_15.12.4.LTS/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/source" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-CLI" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-CLI/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-IO/Include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-IO/Device/tms570ls20x31x/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-IO/Device/tms570ls20x31x/SupportedBoards" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP/protocols/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP/portable/Compiler/CCS" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-FAT/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-FAT/portable/common" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-UDP-Console/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-UART-Console/include" -g --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --enum_type=packed --preproc_with_compile --preproc_dependency="source/os_heap.d" --obj_directory="source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

source/os_list.obj: ../source/os_list.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_15.12.4.LTS/bin/armcl" -mv7R5 --code_state=32 --float_support=VFPv3D16 -O4 --opt_for_speed=0 --fp_mode=relaxed --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_15.12.4.LTS/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/source" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-CLI" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-CLI/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-IO/Include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-IO/Device/tms570ls20x31x/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-IO/Device/tms570ls20x31x/SupportedBoards" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP/protocols/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP/portable/Compiler/CCS" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-FAT/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-FAT/portable/common" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-UDP-Console/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-UART-Console/include" -g --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --enum_type=packed --preproc_with_compile --preproc_dependency="source/os_list.d" --obj_directory="source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

source/os_mpu_wrappers.obj: ../source/os_mpu_wrappers.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_15.12.4.LTS/bin/armcl" -mv7R5 --code_state=32 --float_support=VFPv3D16 -O4 --opt_for_speed=0 --fp_mode=relaxed --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_15.12.4.LTS/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/source" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-CLI" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-CLI/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-IO/Include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-IO/Device/tms570ls20x31x/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-IO/Device/tms570ls20x31x/SupportedBoards" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP/protocols/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP/portable/Compiler/CCS" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-FAT/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-FAT/portable/common" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-UDP-Console/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-UART-Console/include" -g --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --enum_type=packed --preproc_with_compile --preproc_dependency="source/os_mpu_wrappers.d" --obj_directory="source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

source/os_port.obj: ../source/os_port.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_15.12.4.LTS/bin/armcl" -mv7R5 --code_state=32 --float_support=VFPv3D16 -O4 --opt_for_speed=0 --fp_mode=relaxed --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_15.12.4.LTS/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/source" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-CLI" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-CLI/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-IO/Include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-IO/Device/tms570ls20x31x/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-IO/Device/tms570ls20x31x/SupportedBoards" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP/protocols/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP/portable/Compiler/CCS" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-FAT/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-FAT/portable/common" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-UDP-Console/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-UART-Console/include" -g --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --enum_type=packed --preproc_with_compile --preproc_dependency="source/os_port.d" --obj_directory="source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

source/os_portasm.obj: ../source/os_portasm.asm $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_15.12.4.LTS/bin/armcl" -mv7R5 --code_state=32 --float_support=VFPv3D16 -O4 --opt_for_speed=0 --fp_mode=relaxed --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_15.12.4.LTS/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/source" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-CLI" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-CLI/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-IO/Include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-IO/Device/tms570ls20x31x/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-IO/Device/tms570ls20x31x/SupportedBoards" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP/protocols/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP/portable/Compiler/CCS" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-FAT/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-FAT/portable/common" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-UDP-Console/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-UART-Console/include" -g --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --enum_type=packed --preproc_with_compile --preproc_dependency="source/os_portasm.d" --obj_directory="source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

source/os_queue.obj: ../source/os_queue.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_15.12.4.LTS/bin/armcl" -mv7R5 --code_state=32 --float_support=VFPv3D16 -O4 --opt_for_speed=0 --fp_mode=relaxed --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_15.12.4.LTS/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/source" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-CLI" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-CLI/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-IO/Include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-IO/Device/tms570ls20x31x/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-IO/Device/tms570ls20x31x/SupportedBoards" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP/protocols/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP/portable/Compiler/CCS" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-FAT/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-FAT/portable/common" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-UDP-Console/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-UART-Console/include" -g --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --enum_type=packed --preproc_with_compile --preproc_dependency="source/os_queue.d" --obj_directory="source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

source/os_tasks.obj: ../source/os_tasks.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_15.12.4.LTS/bin/armcl" -mv7R5 --code_state=32 --float_support=VFPv3D16 -O4 --opt_for_speed=0 --fp_mode=relaxed --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_15.12.4.LTS/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/source" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-CLI" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-CLI/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-IO/Include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-IO/Device/tms570ls20x31x/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-IO/Device/tms570ls20x31x/SupportedBoards" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP/protocols/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP/portable/Compiler/CCS" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-FAT/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-FAT/portable/common" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-UDP-Console/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-UART-Console/include" -g --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --enum_type=packed --preproc_with_compile --preproc_dependency="source/os_tasks.d" --obj_directory="source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

source/os_timer.obj: ../source/os_timer.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_15.12.4.LTS/bin/armcl" -mv7R5 --code_state=32 --float_support=VFPv3D16 -O4 --opt_for_speed=0 --fp_mode=relaxed --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_15.12.4.LTS/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/source" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-CLI" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-CLI/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-IO/Include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-IO/Device/tms570ls20x31x/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-IO/Device/tms570ls20x31x/SupportedBoards" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP/protocols/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP/portable/Compiler/CCS" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-FAT/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-FAT/portable/common" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-UDP-Console/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-UART-Console/include" -g --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --enum_type=packed --preproc_with_compile --preproc_dependency="source/os_timer.d" --obj_directory="source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

source/rti_runtimestats.obj: ../source/rti_runtimestats.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_15.12.4.LTS/bin/armcl" -mv7R5 --code_state=32 --float_support=VFPv3D16 -O4 --opt_for_speed=0 --fp_mode=relaxed --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_15.12.4.LTS/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/source" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-CLI" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-CLI/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-IO/Include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-IO/Device/tms570ls20x31x/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-IO/Device/tms570ls20x31x/SupportedBoards" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP/protocols/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP/portable/Compiler/CCS" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-TCP" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-FAT/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-FAT/portable/common" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-UDP-Console/include" --include_path="C:/Users/Loszi/workspace_v6_2/LaunchPad_FreeRTOS/FreeRTOS-Plus-UART-Console/include" -g --gcc --diag_warning=225 --diag_wrap=off --display_error_number --abi=eabi --enum_type=packed --preproc_with_compile --preproc_dependency="source/rti_runtimestats.d" --obj_directory="source" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '


