# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/ps_spi.xdc

# Block Designs: bd/ps_spi/ps_spi.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ps_spi || ORIG_REF_NAME==ps_spi} -quiet] -quiet

# IP: bd/ps_spi/ip/ps_spi_processing_system7_0_0/ps_spi_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ps_spi_processing_system7_0_0 || ORIG_REF_NAME==ps_spi_processing_system7_0_0} -quiet] -quiet

# IP: bd/ps_spi/ip/ps_spi_xlconstant_0_0/ps_spi_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ps_spi_xlconstant_0_0 || ORIG_REF_NAME==ps_spi_xlconstant_0_0} -quiet] -quiet

# XDC: bd/ps_spi/ps_spi_ooc.xdc
