# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/uart.xdc

# Block Designs: bd/uart_system/uart_system.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uart_system || ORIG_REF_NAME==uart_system} -quiet] -quiet

# IP: bd/uart_system/ip/uart_system_processing_system7_0_0/uart_system_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uart_system_processing_system7_0_0 || ORIG_REF_NAME==uart_system_processing_system7_0_0} -quiet] -quiet

# XDC: bd/uart_system/uart_system_ooc.xdc
