# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/fpga_sine_wave/fpga_sine_wave.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fpga_sine_wave || ORIG_REF_NAME==fpga_sine_wave} -quiet] -quiet

# IP: bd/fpga_sine_wave/ip/fpga_sine_wave_processing_system7_0_0/fpga_sine_wave_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fpga_sine_wave_processing_system7_0_0 || ORIG_REF_NAME==fpga_sine_wave_processing_system7_0_0} -quiet] -quiet

# IP: bd/fpga_sine_wave/ip/fpga_sine_wave_PmodR2R_0_0/fpga_sine_wave_PmodR2R_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fpga_sine_wave_PmodR2R_0_0 || ORIG_REF_NAME==fpga_sine_wave_PmodR2R_0_0} -quiet] -quiet

# IP: bd/fpga_sine_wave/ip/fpga_sine_wave_ps7_0_axi_periph_0/fpga_sine_wave_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fpga_sine_wave_ps7_0_axi_periph_0 || ORIG_REF_NAME==fpga_sine_wave_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/fpga_sine_wave/ip/fpga_sine_wave_rst_ps7_0_50M_0/fpga_sine_wave_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fpga_sine_wave_rst_ps7_0_50M_0 || ORIG_REF_NAME==fpga_sine_wave_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/fpga_sine_wave/ip/fpga_sine_wave_auto_pc_0/fpga_sine_wave_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fpga_sine_wave_auto_pc_0 || ORIG_REF_NAME==fpga_sine_wave_auto_pc_0} -quiet] -quiet

# XDC: bd/fpga_sine_wave/fpga_sine_wave_ooc.xdc
