set_property SRC_FILE_INFO {cfile:/home/koitt/Vivado_Workspace/uart/uart.srcs/constrs_1/new/uart.xdc rfile:../../../uart.srcs/constrs_1/new/uart.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V12 [get_ports UART_0_0_rxd]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W16 [get_ports UART_0_0_txd]
