################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Each subdirectory must supply rules for building sources it contributes
Teknic_NEMA_M2310_CtrlAppTrg_ert_rtw/Teknic_NEMA_M2310_CtrlAppTrg.obj: ../Teknic_NEMA_M2310_CtrlAppTrg_ert_rtw/Teknic_NEMA_M2310_CtrlAppTrg.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_15.9.0.STS/bin/armcl" -mv7R5 --code_state=32 --float_support=VFPv3D16 -O4 --opt_for_speed=0 --fp_mode=relaxed --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_15.9.0.STS/include" --include_path="C:/Users/loszi/workspace_v6_0/TMP570LC4357_FreeRTOS/Teknic_NEMA_M2310_CtrlAppTrg_ert_rtw" --include_path="C:/Users/loszi/workspace_v6_0/TMP570LC4357_FreeRTOS/FreeRTOS-Plus-UART-Console" --include_path="C:/Users/loszi/workspace_v6_0/TMP570LC4357_FreeRTOS/source" --include_path="C:/Users/loszi/workspace_v6_0/TMP570LC4357_FreeRTOS/include" --include_path="C:/Users/loszi/workspace_v6_0/TMP570LC4357_FreeRTOS/FreeRTOS-Plus-CLI" --include_path="C:/Users/loszi/workspace_v6_0/TMP570LC4357_FreeRTOS/FreeRTOS-Plus-IO/Include" --include_path="C:/Users/loszi/workspace_v6_0/TMP570LC4357_FreeRTOS/FreeRTOS-Plus-IO/Device/tms570ls20x31x/include" --include_path="C:/Users/loszi/workspace_v6_0/TMP570LC4357_FreeRTOS/FreeRTOS-Plus-IO/Device/tms570ls20x31x/SupportedBoards" --include_path="C:/Users/loszi/workspace_v6_0/TMP570LC4357_FreeRTOS/FreeRTOS-Plus-CLI/include" --include_path="C:/Users/loszi/workspace_v6_0/TMP570LC4357_FreeRTOS/FreeRTOS-Plus-TCP/include" --include_path="C:/Users/loszi/workspace_v6_0/TMP570LC4357_FreeRTOS/FreeRTOS-Plus-TCP/protocols/include" --include_path="C:/Users/loszi/workspace_v6_0/TMP570LC4357_FreeRTOS/FreeRTOS-Plus-TCP/portable/Compiler/CCS" --include_path="C:/Users/loszi/workspace_v6_0/TMP570LC4357_FreeRTOS/FreeRTOS-Plus-TCP" --include_path="C:/Users/loszi/workspace_v6_0/TMP570LC4357_FreeRTOS/FreeRTOS-Plus-FAT/include" --include_path="C:/Users/loszi/workspace_v6_0/TMP570LC4357_FreeRTOS/FreeRTOS-Plus-FAT/portable/common" --include_path="C:/Users/loszi/workspace_v6_0/TMP570LC4357_FreeRTOS/FreeRTOS-Plus-UDP-Console/include" --include_path="C:/Users/loszi/workspace_v6_0/TMP570LC4357_FreeRTOS/FreeRTOS-Plus-UART-Console/include" -g --gcc --display_error_number --diag_wrap=off --diag_warning=225 --abi=eabi --enum_type=packed --preproc_with_compile --preproc_dependency="Teknic_NEMA_M2310_CtrlAppTrg_ert_rtw/Teknic_NEMA_M2310_CtrlAppTrg.pp" --obj_directory="Teknic_NEMA_M2310_CtrlAppTrg_ert_rtw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

Teknic_NEMA_M2310_CtrlAppTrg_ert_rtw/Teknic_NEMA_M2310_CtrlAppTrg_data.obj: ../Teknic_NEMA_M2310_CtrlAppTrg_ert_rtw/Teknic_NEMA_M2310_CtrlAppTrg_data.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_15.9.0.STS/bin/armcl" -mv7R5 --code_state=32 --float_support=VFPv3D16 -O4 --opt_for_speed=0 --fp_mode=relaxed --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_15.9.0.STS/include" --include_path="C:/Users/loszi/workspace_v6_0/TMP570LC4357_FreeRTOS/Teknic_NEMA_M2310_CtrlAppTrg_ert_rtw" --include_path="C:/Users/loszi/workspace_v6_0/TMP570LC4357_FreeRTOS/FreeRTOS-Plus-UART-Console" --include_path="C:/Users/loszi/workspace_v6_0/TMP570LC4357_FreeRTOS/source" --include_path="C:/Users/loszi/workspace_v6_0/TMP570LC4357_FreeRTOS/include" --include_path="C:/Users/loszi/workspace_v6_0/TMP570LC4357_FreeRTOS/FreeRTOS-Plus-CLI" --include_path="C:/Users/loszi/workspace_v6_0/TMP570LC4357_FreeRTOS/FreeRTOS-Plus-IO/Include" --include_path="C:/Users/loszi/workspace_v6_0/TMP570LC4357_FreeRTOS/FreeRTOS-Plus-IO/Device/tms570ls20x31x/include" --include_path="C:/Users/loszi/workspace_v6_0/TMP570LC4357_FreeRTOS/FreeRTOS-Plus-IO/Device/tms570ls20x31x/SupportedBoards" --include_path="C:/Users/loszi/workspace_v6_0/TMP570LC4357_FreeRTOS/FreeRTOS-Plus-CLI/include" --include_path="C:/Users/loszi/workspace_v6_0/TMP570LC4357_FreeRTOS/FreeRTOS-Plus-TCP/include" --include_path="C:/Users/loszi/workspace_v6_0/TMP570LC4357_FreeRTOS/FreeRTOS-Plus-TCP/protocols/include" --include_path="C:/Users/loszi/workspace_v6_0/TMP570LC4357_FreeRTOS/FreeRTOS-Plus-TCP/portable/Compiler/CCS" --include_path="C:/Users/loszi/workspace_v6_0/TMP570LC4357_FreeRTOS/FreeRTOS-Plus-TCP" --include_path="C:/Users/loszi/workspace_v6_0/TMP570LC4357_FreeRTOS/FreeRTOS-Plus-FAT/include" --include_path="C:/Users/loszi/workspace_v6_0/TMP570LC4357_FreeRTOS/FreeRTOS-Plus-FAT/portable/common" --include_path="C:/Users/loszi/workspace_v6_0/TMP570LC4357_FreeRTOS/FreeRTOS-Plus-UDP-Console/include" --include_path="C:/Users/loszi/workspace_v6_0/TMP570LC4357_FreeRTOS/FreeRTOS-Plus-UART-Console/include" -g --gcc --display_error_number --diag_wrap=off --diag_warning=225 --abi=eabi --enum_type=packed --preproc_with_compile --preproc_dependency="Teknic_NEMA_M2310_CtrlAppTrg_ert_rtw/Teknic_NEMA_M2310_CtrlAppTrg_data.pp" --obj_directory="Teknic_NEMA_M2310_CtrlAppTrg_ert_rtw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

Teknic_NEMA_M2310_CtrlAppTrg_ert_rtw/rtGetInf.obj: ../Teknic_NEMA_M2310_CtrlAppTrg_ert_rtw/rtGetInf.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_15.9.0.STS/bin/armcl" -mv7R5 --code_state=32 --float_support=VFPv3D16 -O4 --opt_for_speed=0 --fp_mode=relaxed --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_15.9.0.STS/include" --include_path="C:/Users/loszi/workspace_v6_0/TMP570LC4357_FreeRTOS/Teknic_NEMA_M2310_CtrlAppTrg_ert_rtw" --include_path="C:/Users/loszi/workspace_v6_0/TMP570LC4357_FreeRTOS/FreeRTOS-Plus-UART-Console" --include_path="C:/Users/loszi/workspace_v6_0/TMP570LC4357_FreeRTOS/source" --include_path="C:/Users/loszi/workspace_v6_0/TMP570LC4357_FreeRTOS/include" --include_path="C:/Users/loszi/workspace_v6_0/TMP570LC4357_FreeRTOS/FreeRTOS-Plus-CLI" --include_path="C:/Users/loszi/workspace_v6_0/TMP570LC4357_FreeRTOS/FreeRTOS-Plus-IO/Include" --include_path="C:/Users/loszi/workspace_v6_0/TMP570LC4357_FreeRTOS/FreeRTOS-Plus-IO/Device/tms570ls20x31x/include" --include_path="C:/Users/loszi/workspace_v6_0/TMP570LC4357_FreeRTOS/FreeRTOS-Plus-IO/Device/tms570ls20x31x/SupportedBoards" --include_path="C:/Users/loszi/workspace_v6_0/TMP570LC4357_FreeRTOS/FreeRTOS-Plus-CLI/include" --include_path="C:/Users/loszi/workspace_v6_0/TMP570LC4357_FreeRTOS/FreeRTOS-Plus-TCP/include" --include_path="C:/Users/loszi/workspace_v6_0/TMP570LC4357_FreeRTOS/FreeRTOS-Plus-TCP/protocols/include" --include_path="C:/Users/loszi/workspace_v6_0/TMP570LC4357_FreeRTOS/FreeRTOS-Plus-TCP/portable/Compiler/CCS" --include_path="C:/Users/loszi/workspace_v6_0/TMP570LC4357_FreeRTOS/FreeRTOS-Plus-TCP" --include_path="C:/Users/loszi/workspace_v6_0/TMP570LC4357_FreeRTOS/FreeRTOS-Plus-FAT/include" --include_path="C:/Users/loszi/workspace_v6_0/TMP570LC4357_FreeRTOS/FreeRTOS-Plus-FAT/portable/common" --include_path="C:/Users/loszi/workspace_v6_0/TMP570LC4357_FreeRTOS/FreeRTOS-Plus-UDP-Console/include" --include_path="C:/Users/loszi/workspace_v6_0/TMP570LC4357_FreeRTOS/FreeRTOS-Plus-UART-Console/include" -g --gcc --display_error_number --diag_wrap=off --diag_warning=225 --abi=eabi --enum_type=packed --preproc_with_compile --preproc_dependency="Teknic_NEMA_M2310_CtrlAppTrg_ert_rtw/rtGetInf.pp" --obj_directory="Teknic_NEMA_M2310_CtrlAppTrg_ert_rtw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

Teknic_NEMA_M2310_CtrlAppTrg_ert_rtw/rtGetNaN.obj: ../Teknic_NEMA_M2310_CtrlAppTrg_ert_rtw/rtGetNaN.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_15.9.0.STS/bin/armcl" -mv7R5 --code_state=32 --float_support=VFPv3D16 -O4 --opt_for_speed=0 --fp_mode=relaxed --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_15.9.0.STS/include" --include_path="C:/Users/loszi/workspace_v6_0/TMP570LC4357_FreeRTOS/Teknic_NEMA_M2310_CtrlAppTrg_ert_rtw" --include_path="C:/Users/loszi/workspace_v6_0/TMP570LC4357_FreeRTOS/FreeRTOS-Plus-UART-Console" --include_path="C:/Users/loszi/workspace_v6_0/TMP570LC4357_FreeRTOS/source" --include_path="C:/Users/loszi/workspace_v6_0/TMP570LC4357_FreeRTOS/include" --include_path="C:/Users/loszi/workspace_v6_0/TMP570LC4357_FreeRTOS/FreeRTOS-Plus-CLI" --include_path="C:/Users/loszi/workspace_v6_0/TMP570LC4357_FreeRTOS/FreeRTOS-Plus-IO/Include" --include_path="C:/Users/loszi/workspace_v6_0/TMP570LC4357_FreeRTOS/FreeRTOS-Plus-IO/Device/tms570ls20x31x/include" --include_path="C:/Users/loszi/workspace_v6_0/TMP570LC4357_FreeRTOS/FreeRTOS-Plus-IO/Device/tms570ls20x31x/SupportedBoards" --include_path="C:/Users/loszi/workspace_v6_0/TMP570LC4357_FreeRTOS/FreeRTOS-Plus-CLI/include" --include_path="C:/Users/loszi/workspace_v6_0/TMP570LC4357_FreeRTOS/FreeRTOS-Plus-TCP/include" --include_path="C:/Users/loszi/workspace_v6_0/TMP570LC4357_FreeRTOS/FreeRTOS-Plus-TCP/protocols/include" --include_path="C:/Users/loszi/workspace_v6_0/TMP570LC4357_FreeRTOS/FreeRTOS-Plus-TCP/portable/Compiler/CCS" --include_path="C:/Users/loszi/workspace_v6_0/TMP570LC4357_FreeRTOS/FreeRTOS-Plus-TCP" --include_path="C:/Users/loszi/workspace_v6_0/TMP570LC4357_FreeRTOS/FreeRTOS-Plus-FAT/include" --include_path="C:/Users/loszi/workspace_v6_0/TMP570LC4357_FreeRTOS/FreeRTOS-Plus-FAT/portable/common" --include_path="C:/Users/loszi/workspace_v6_0/TMP570LC4357_FreeRTOS/FreeRTOS-Plus-UDP-Console/include" --include_path="C:/Users/loszi/workspace_v6_0/TMP570LC4357_FreeRTOS/FreeRTOS-Plus-UART-Console/include" -g --gcc --display_error_number --diag_wrap=off --diag_warning=225 --abi=eabi --enum_type=packed --preproc_with_compile --preproc_dependency="Teknic_NEMA_M2310_CtrlAppTrg_ert_rtw/rtGetNaN.pp" --obj_directory="Teknic_NEMA_M2310_CtrlAppTrg_ert_rtw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

Teknic_NEMA_M2310_CtrlAppTrg_ert_rtw/rt_nonfinite.obj: ../Teknic_NEMA_M2310_CtrlAppTrg_ert_rtw/rt_nonfinite.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Compiler'
	"C:/ti/ccsv6/tools/compiler/ti-cgt-arm_15.9.0.STS/bin/armcl" -mv7R5 --code_state=32 --float_support=VFPv3D16 -O4 --opt_for_speed=0 --fp_mode=relaxed --include_path="C:/ti/ccsv6/tools/compiler/ti-cgt-arm_15.9.0.STS/include" --include_path="C:/Users/loszi/workspace_v6_0/TMP570LC4357_FreeRTOS/Teknic_NEMA_M2310_CtrlAppTrg_ert_rtw" --include_path="C:/Users/loszi/workspace_v6_0/TMP570LC4357_FreeRTOS/FreeRTOS-Plus-UART-Console" --include_path="C:/Users/loszi/workspace_v6_0/TMP570LC4357_FreeRTOS/source" --include_path="C:/Users/loszi/workspace_v6_0/TMP570LC4357_FreeRTOS/include" --include_path="C:/Users/loszi/workspace_v6_0/TMP570LC4357_FreeRTOS/FreeRTOS-Plus-CLI" --include_path="C:/Users/loszi/workspace_v6_0/TMP570LC4357_FreeRTOS/FreeRTOS-Plus-IO/Include" --include_path="C:/Users/loszi/workspace_v6_0/TMP570LC4357_FreeRTOS/FreeRTOS-Plus-IO/Device/tms570ls20x31x/include" --include_path="C:/Users/loszi/workspace_v6_0/TMP570LC4357_FreeRTOS/FreeRTOS-Plus-IO/Device/tms570ls20x31x/SupportedBoards" --include_path="C:/Users/loszi/workspace_v6_0/TMP570LC4357_FreeRTOS/FreeRTOS-Plus-CLI/include" --include_path="C:/Users/loszi/workspace_v6_0/TMP570LC4357_FreeRTOS/FreeRTOS-Plus-TCP/include" --include_path="C:/Users/loszi/workspace_v6_0/TMP570LC4357_FreeRTOS/FreeRTOS-Plus-TCP/protocols/include" --include_path="C:/Users/loszi/workspace_v6_0/TMP570LC4357_FreeRTOS/FreeRTOS-Plus-TCP/portable/Compiler/CCS" --include_path="C:/Users/loszi/workspace_v6_0/TMP570LC4357_FreeRTOS/FreeRTOS-Plus-TCP" --include_path="C:/Users/loszi/workspace_v6_0/TMP570LC4357_FreeRTOS/FreeRTOS-Plus-FAT/include" --include_path="C:/Users/loszi/workspace_v6_0/TMP570LC4357_FreeRTOS/FreeRTOS-Plus-FAT/portable/common" --include_path="C:/Users/loszi/workspace_v6_0/TMP570LC4357_FreeRTOS/FreeRTOS-Plus-UDP-Console/include" --include_path="C:/Users/loszi/workspace_v6_0/TMP570LC4357_FreeRTOS/FreeRTOS-Plus-UART-Console/include" -g --gcc --display_error_number --diag_wrap=off --diag_warning=225 --abi=eabi --enum_type=packed --preproc_with_compile --preproc_dependency="Teknic_NEMA_M2310_CtrlAppTrg_ert_rtw/rt_nonfinite.pp" --obj_directory="Teknic_NEMA_M2310_CtrlAppTrg_ert_rtw" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '


